config/routes.rb
Rails.application.routes.draw do
  devise_for :supervisors
	root :to => 'static#index'

  namespace :api do
  	namespace :v1 do
  		resources :users
			resources :posts
      resources :vehicles
      resources :charge_points do
				member do
					get 'authorize'
					get 'boot_notification'
					get 'heartbeat'
					get 'start_transaction'
					get 'meter_values'
					get 'stop_transaction'
          get 'status_notification'
          get 'firmware_status_notification'
          get 'diagnostics_status_notification'
          get 'data_transfer'

          get 'Authorize'
					get 'BootNotification'
          get 'Heartbeat'
          get 'StartTransaction'
          get 'MeterValues'
          get 'StopTransaction'
          get 'StatusNotification'
          get 'FirmwareStatusNotification'
          get 'DiagnosticsStatusNotification'
          get 'DataTransfer'
				end
			end
			resources :trades
  		resources :records
      resources :connectors
   end
  end

end

app/models/charge_point.rb
class ChargePoint < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :vehicles
  has_many :trades
  has_many :connectors
  accepts_nested_attributes_for :users
end

app/controllers/api/v1/charge_points_controller.rb
class Api::V1::ChargePointsController < ApplicationController
  protect_from_forgery

  before_action :set_charge_point, only: [:show, :edit, :update, :destroy,
    :authorize, :boot_notification, :heartbeat, :meter_values, :start_transaction, :stop_transaction,
    :BootNotification, :Authorize, :Heartbeat, :MeterValues, :StartTransaction, :StopTransaction]
  respond_to :json, :html

  # GET /charge_points
  # GET /charge_points.json
  def index
    @charge_points = ChargePoint.all
    respond_with @charge_points
  end

  # GET /charge_points/1
  # GET /charge_points/1.json
  def show
    #respond_with(@charge_point, @charge_point.vehicles)
    respond_to do |format|
      format.json { render json: @charge_point }
    end
  end

  # GET /charge_points/new
  def new
    @charge_point = ChargePoint.new
    respond_with @charge_point
  end

  # GET /charge_points/1/edit
  def edit
    respond_with @charge_point
  end

  # POST /charge_points
  # POST /charge_points.json
  def create
    @charge_point = ChargePoint.new(charge_point_params)

    respond_to do |format|
      if @charge_point.save
        format.json { render json: @charge_point, status: :created }
      else
        format.json { render json: @charge_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charge_points/1
  # PATCH/PUT /charge_points/1.json
  def update
    respond_to do |format|
      if @charge_point.update(charge_point_params)
        #format.json { render :show, status: :ok, location: nil}
        format.json { render json: @charge_point, status: :ok }
      else
        format.json { render json: @charge_point.errors, status: :unprocessable_entity }
      end
    end
    # @charge_point.update(charge_point_params)
    # respond_with @charge_point
  end

  # DELETE /charge_points/1
  # DELETE /charge_points/1.json
  def destroy
    @charge_point.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def authorize
    id_tag = params[:id_tag]

    respond_to do |format|
      if id_tag
        @user = User.find_by(id_tag: id_tag)
        if @user && @user.expiry_date > Date.today
          result = {"id_tag_info" => { "status" => "Accepted", "expiry_date" => @user.expiry_date, "parent_id_tag" => "" }}
        elsif @user && user.expiry_date < Date.today
          result = {"id_tag_info" => { "status" => "Expired", "expiry_date" => @user.expiry_date, "parent_id_tag" => "" }}
        else
          result = {"id_tag_info" => { "status" => "Blocked", "expiry_date" => "", "parent_id_tag" => "" }}
        end
      else
        result = {"id_tag_info" => { "status" => "Invalid", "expiry_date" => "", "parent_id_tag" => "" }}
      end
      format.json { render json: result }
    end
  end

  def Authorize
    id_tag = params[:id_tag]

    respond_to do |format|
      if id_tag
        @user = User.find_by(id_tag: id_tag)
        if @user && @user.expiry_date > Date.today
          result = {"id_tag_info" => { "status" => "Accepted", "expiry_date" => @user.expiry_date, "parent_id_tag" => "" }}
        elsif @user && user.expiry_date < Date.today
          result = {"id_tag_info" => { "status" => "Expired", "expiry_date" => @user.expiry_date, "parent_id_tag" => "" }}
        else
          result = {"id_tag_info" => { "status" => "Blocked", "expiry_date" => "", "parent_id_tag" => "" }}
        end
      else
        result = {"id_tag_info" => { "status" => "Invalid", "expiry_date" => "", "parent_id_tag" => "" }}
      end
      format.json { render json: result }
    end
  end

  def boot_notification
    charge_point_vendor = params[:charge_point_vendor]
    charge_point_model = params[:charge_point_model]
    charge_point_serial_number = params[:charge_point_serial_number]
    charge_box_serial_number = params[:charge_box_serial_number]

    respond_to do |format|
      if charge_point_vendor == @charge_point[:charge_point_vendor]
        @charge_point.update(status: "Accepted")
        result = { "status" => "Accepted", "current_time" => Time.now,  "heartbeart_interval" => @charge_point[:heartbeat_interval]}
      else
        result = { "status" => "Rejected", "current_time" => Time.now,  "heartbeart_interval" => @charge_point[:heartbeat_interval]}
      end
      format.json { render :json => result }
    end
  end

  def BootNotification
    charge_point_vendor = params[:charge_point_vendor]
    charge_point_model = params[:charge_point_model]
    charge_point_serial_number = params[:charge_point_serial_number]
    charge_box_serial_number = params[:charge_box_serial_number]
    firmware_version = params[:firmware_version]
    iccid = params[:iccid]
    imsi = params[:imsi]
    meter_type = params[:meter_type]
    meter_serial_number = params[:meter_serial_number]

    respond_to do |format|
      if charge_point_vendor == @charge_point[:charge_point_vendor] &&
        charge_point_model == @charge_point[:charge_point_model] &&
        charge_point_serial_number == @charge_point[:charge_box_serial_number] &&
        charge_box_serial_number == @charge_point[:charge_box_serial_number] &&
        firmware_version == @charge_point[:firmware_version] &&
        iccid == @charge_point[:iccid] &&
        imsi == @charge_point[:imsi] &&
        meter_type == @charge_point[:meter_type] &&
        meter_serial_number == @charge_point[:meter_serial_number]

        @charge_point.update(status: "Accepted")
        result = { "status" => "Accepted", "current_time" => Time.now,  "heartbeart_interval" => @charge_point[:heartbeat_interval]}
      else
        result = { "status" => "Rejected", "current_time" => Time.now,  "heartbeart_interval" => @charge_point[:heartbeat_interval]}
      end
      format.json { render :json => result }
    end
  end

  def heartbeat
    respond_to do |format|
      result = { "current_time" => Time.now, "heartbeat_interval" => @charge_point[:heartbeat_interval]}
      format.json { render json: result }
    end
  end

  def Heartbeat
    respond_to do |format|
      result = { "current_time" => Time.now, "heartbeat_interval" => @charge_point[:heartbeat_interval]}
      format.json { render json: result }
    end
  end

  def meter_values
    # Mandatory Parameters
    connector_id = params[:connector_id]
    # Optional Parameters but self mandatory
    transaction_id = params[:transaction_id]
    values = params[:values]
    current = values[:current]
    power = values[:power]

    if current.include? ","
      current[','] = '.'
    end

    if power.include? ","
      power[','] = '.'
    end

    respond_to do |format|
      if connector_id && transaction_id && values
        @trade = Trade.find(transaction_id)
        @connector = Connector.find(connector_id)
        @record = Record.create(trade_id: @trade.id, power: values[:power], current: values[:current])
        result = {}
        format.json { render json: result }
      else
        result = { "error" => "parameters required" }
        format.json { render json: result }
      end
    end
  end

  def MeterValues
    # Mandatory Parameters
    connector_id = params[:connector_id]
    # Optional Parameters but self mandatory
    transaction_id = params[:transaction_id]
    values = params[:values]
    current = values[:current]
    power = values[:power]

    if current.include? ","
      current[','] = '.'
    end

    if power.include? ","
      power[','] = '.'
    end

    respond_to do |format|
      if connector_id && transaction_id && values
        @trade = Trade.find(transaction_id)
        @connector = Connector.find(connector_id)
        @record = Record.create(trade_id: @trade.id, power: values[:power], current: values[:current])
        result = {}
        format.json { render json: result }
      else
        result = { "error" => "parameters required" }
        format.json { render json: result }
      end
    end
  end

  def start_transaction
    # Mandatory Parameters
    id_tag = params[:id_tag]
    connector_id = params[:connector_id]
    #timestamp = params[:timestamp]
    meter_start = params[:meter_start]
    # Optinal Parameters
    reservation_id = params[:reservation_id]

    # Optional Parameters but self Mandatory
    # vehicle_id = params[:vehicle_id]
    vehicle_name = params[:vehicle_name]
    vehicle_id = Vehicle.find_by name: vehicle_name

    respond_to do |format|
      if id_tag && connector_id && meter_start
        @user = User.find_by(id_tag: id_tag)
        if @user
          if @user.expiry_date > Date.today
            @trade = Trade.create(user_id: @user.id, charge_point_id: @charge_point.id,
            connector_id: connector_id, energy: 0, bill: 0, status: 'Started', meter_start: meter_start)
            if vehicle_id and Vehicle.find(vehicle_id)
              @trade.update(vehicle_id: vehicle_id)
            else
              result = {"error" => "no vehicle found"}
            end
            result = {
              "transaction_id" => @trade.id,
              "id_tag_info" => { "status" => "Accepted", "expiry_date" => @user.expiry_date, "parent_id_tag" => "" }
            }
            #result = { "id_tag" => id_tag }
            format.json { render json: result }
          else @user.expiry_date < Date.tody
            result = {
              "transaction_id" => "null",
              "id_tag_info" => { "status" => "Expired", "expiry_date" => @user.expiry_date, "parent_id_tag" => "" }
            }
            format.json { render json: result }
          end
        else
          result = {
            "transaction_id" => "null",
            "id_tag_info" => { "status" => "Invalid", "expiry_date" => "", "parent_id_tag" => "" }
          }
          format.json { render json: result }
        end
      else
        result = { "error" => "parameters required"}
        format.json { render json: result }
      end
    end
  end

  def StartTransaction
    # Mandatory Parameters
    id_tag = params[:id_tag]

app/controllers/charge_points_controller.rb
class ChargePointsController < ApplicationController
  before_action :set_charge_point, only: [:show, :edit, :update, :destroy]

  # GET /charge_points
  # GET /charge_points.json
  def index
    @charge_points = ChargePoint.all
  end

  # GET /charge_points/1
  # GET /charge_points/1.json
  def show
  end

  # GET /charge_points/new
  def new
    @charge_point = ChargePoint.new
  end

  # GET /charge_points/1/edit
  def edit
  end

  # POST /charge_points
  # POST /charge_points.json
  def create
    @charge_point = ChargePoint.new(charge_point_params)

    respond_to do |format|
      if @charge_point.save
        format.html { redirect_to @charge_point, notice: 'Charge point was successfully created.' }
        format.json { render :show, status: :created, location: @charge_point }
      else
        format.html { render :new }
        format.json { render json: @charge_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charge_points/1
  # PATCH/PUT /charge_points/1.json
  def update
    respond_to do |format|
      if @charge_point.update(charge_point_params)
        format.html { redirect_to @charge_point, notice: 'Charge point was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge_point }
      else
        format.html { render :edit }
        format.json { render json: @charge_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charge_points/1
  # DELETE /charge_points/1.json
  def destroy
    @charge_point.destroy
    respond_to do |format|
      format.html { redirect_to charge_points_url, notice: 'Charge point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge_point
      @charge_point = ChargePoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_point_params
      params.require(:charge_point).permit(:name, :status, :charge_point_vendor, :charge_point_model, :charge_point_serial_number, :firmware_version, :iccid, :imsi, :meter_type, :meter_serial_number, :heartbeat_interval, :charge_box_serial_number)
    end
end

app/helpers/charge_points_helper.rb
module ChargePointsHelper
end

app/views/charge_points/_form.html.erb
<%= form_for(@charge_point) do |f| %>
  <% if @charge_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge_point.errors.count, "error") %> prohibited this charge_point from being saved:</h2>

      <ul>
      <% @charge_point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :charge_point_vendor %><br>
    <%= f.text_field :charge_point_vendor %>
  </div>
  <div class="field">
    <%= f.label :charge_point_model %><br>
    <%= f.text_field :charge_point_model %>
  </div>
  <div class="field">
    <%= f.label :charge_point_serial_number %><br>
    <%= f.text_field :charge_point_serial_number %>
  </div>
  <div class="field">
    <%= f.label :firmware_version %><br>
    <%= f.text_field :firmware_version %>
  </div>
  <div class="field">
    <%= f.label :iccid %><br>
    <%= f.text_field :iccid %>
  </div>
  <div class="field">
    <%= f.label :imsi %><br>
    <%= f.text_field :imsi %>
  </div>
  <div class="field">
    <%= f.label :meter_type %><br>
    <%= f.text_field :meter_type %>
  </div>
  <div class="field">
    <%= f.label :meter_serial_number %><br>
    <%= f.text_field :meter_serial_number %>
  </div>
  <div class="field">
    <%= f.label :heartbeat_interval %><br>
    <%= f.number_field :heartbeat_interval %>
  </div>
  <div class="field">
    <%= f.label :charge_box_serial_number %><br>
    <%= f.text_field :charge_box_serial_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charge_points/edit.html.erb
<h1>Editing charge_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge_point %> |
<%= link_to 'Back', charge_points_path %>

app/views/charge_points/index.html.erb
<h1>Listing charge_points</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Charge point vendor</th>
      <th>Charge point model</th>
      <th>Charge point serial number</th>
      <th>Firmware version</th>
      <th>Iccid</th>
      <th>Imsi</th>
      <th>Meter type</th>
      <th>Meter serial number</th>
      <th>Heartbeat interval</th>
      <th>Charge box serial number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charge_points.each do |charge_point| %>
      <tr>
        <td><%= charge_point.status %></td>
        <td><%= charge_point.charge_point_vendor %></td>
        <td><%= charge_point.charge_point_model %></td>
        <td><%= charge_point.charge_point_serial_number %></td>
        <td><%= charge_point.firmware_version %></td>
        <td><%= charge_point.iccid %></td>
        <td><%= charge_point.imsi %></td>
        <td><%= charge_point.meter_type %></td>
        <td><%= charge_point.meter_serial_number %></td>
        <td><%= charge_point.heartbeat_interval %></td>
        <td><%= charge_point.charge_box_serial_number %></td>
        <td><%= link_to 'Show', charge_point %></td>
        <td><%= link_to 'Edit', edit_charge_point_path(charge_point) %></td>
        <td><%= link_to 'Destroy', charge_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge point', new_charge_point_path %>

app/views/charge_points/new.html.erb
<h1>New charge_point</h1>

<%= render 'form' %>

<%= link_to 'Back', charge_points_path %>

app/views/charge_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @charge_point.status %>
</p>

<p>
  <strong>Charge point vendor:</strong>
  <%= @charge_point.charge_point_vendor %>
</p>

<p>
  <strong>Charge point model:</strong>
  <%= @charge_point.charge_point_model %>
</p>

<p>
  <strong>Charge point serial number:</strong>
  <%= @charge_point.charge_point_serial_number %>
</p>

<p>
  <strong>Firmware version:</strong>
  <%= @charge_point.firmware_version %>
</p>

<p>
  <strong>Iccid:</strong>
  <%= @charge_point.iccid %>
</p>

<p>
  <strong>Imsi:</strong>
  <%= @charge_point.imsi %>
</p>

<p>
  <strong>Meter type:</strong>
  <%= @charge_point.meter_type %>
</p>

<p>
  <strong>Meter serial number:</strong>
  <%= @charge_point.meter_serial_number %>
</p>

<p>
  <strong>Heartbeat interval:</strong>
  <%= @charge_point.heartbeat_interval %>
</p>

<p>
  <strong>Charge box serial number:</strong>
  <%= @charge_point.charge_box_serial_number %>
</p>

<%= link_to 'Edit', edit_charge_point_path(@charge_point) %> |
<%= link_to 'Back', charge_points_path %>