config/routes.rb
Rails.application.routes.draw do
  devise_for :supervisors
	root :to => 'static#index'

  namespace :api do
  	namespace :v1 do
  		resources :users
			resources :posts
      resources :vehicles
      resources :charge_points do
				member do
					get 'authorize'
					get 'boot_notification'
					get 'heartbeat'
					get 'start_transaction'
					get 'meter_values'
					get 'stop_transaction'
          get 'status_notification'
          get 'firmware_status_notification'
          get 'diagnostics_status_notification'
          get 'data_transfer'

          get 'Authorize'
					get 'BootNotification'
          get 'Heartbeat'
          get 'StartTransaction'
          get 'MeterValues'
          get 'StopTransaction'
          get 'StatusNotification'
          get 'FirmwareStatusNotification'
          get 'DiagnosticsStatusNotification'
          get 'DataTransfer'
				end
			end
			resources :trades
  		resources :records
      resources :connectors
   end
  end

end

app/models/charge_point.rb
class ChargePoint < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :vehicles
  has_many :trades
  has_many :connectors
  accepts_nested_attributes_for :users
end

app/models/connector.rb
class Connector < ActiveRecord::Base
  belongs_to :charge_point
  has_many :trades
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :author
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :trade
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  belongs_to :charge_point
  belongs_to :user
  belongs_to :vehicle
  belongs_to :connector
  has_many :records
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :charge_point
  belongs_to :user
  belongs_to :vehicle
end

app/models/user.rb
class User < ActiveRecord::Base
  #before_save { self.email = email.downcase }
  #validates :name, presence: true, length: { maximum: 50 }
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  #                  uniqueness: { case_sensitive: false }
  has_secure_password :validations => false
  #validates :password, length: { minimum: 6 }, :if => :password

  has_and_belongs_to_many :vehicles
  has_and_belongs_to_many :charge_points
  has_many :trades
  accepts_nested_attributes_for :charge_points
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  # has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  # validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_many :trades
  has_and_belongs_to_many :users
  has_and_belongs_to_many :charge_points
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	respond_to :json

	def index
		respond_with Post.all
	end

	def show
		respond_with Post.find(params[:id])
	end

	def create
		respond_with Post.create(post_params)
	end

	def update
		respond_with Post.update(params[:id], post_params)
	end

	def destroy
		respond_with Post.destroy(params[:id])
	end

	private
	def post_params
		params.require(:post).permit(:title, :intro, :extended, :published_at, :author)
	end
end

app/controllers/task_controller.rb
class TaskController < WebsocketRails::BaseController
  def create
    # The `message` method contains the data received
    task = Task.new message
    if task.save
      send_message :create_success, task, :namespace => :tasks
    else
      send_message :create_fail, task, :namespace => :tasks
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charge_points_helper.rb
module ChargePointsHelper
end

app/helpers/connectors_helper.rb
module ConnectorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_id %><br>
    <%= f.text_field :transaction_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :energy %><br>
    <%= f.text_field :energy %>
  </div>
  <div class="field">
    <%= f.label :bill %><br>
    <%= f.text_field :bill %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <thead>
    <tr>
      <th>Transaction</th>
      <th>Status</th>
      <th>Energy</th>
      <th>Bill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.transaction_id %></td>
        <td><%= transaction.status %></td>
        <td><%= transaction.energy %></td>
        <td><%= transaction.bill %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction:</strong>
  <%= @transaction.transaction_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @transaction.status %>
</p>

<p>
  <strong>Energy:</strong>
  <%= @transaction.energy %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @transaction.bill %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>