config/routes.rb
Rails.application.routes.draw do
  devise_for :supervisors
	root :to => 'static#index'

  namespace :api do
  	namespace :v1 do
  		resources :users
			resources :posts
      resources :vehicles
      resources :charge_points do
				member do
					get 'authorize'
					get 'boot_notification'
					get 'heartbeat'
					get 'start_transaction'
					get 'meter_values'
					get 'stop_transaction'
          get 'status_notification'
          get 'firmware_status_notification'
          get 'diagnostics_status_notification'
          get 'data_transfer'

          get 'Authorize'
					get 'BootNotification'
          get 'Heartbeat'
          get 'StartTransaction'
          get 'MeterValues'
          get 'StopTransaction'
          get 'StatusNotification'
          get 'FirmwareStatusNotification'
          get 'DiagnosticsStatusNotification'
          get 'DataTransfer'
				end
			end
			resources :trades
  		resources :records
      resources :connectors
   end
  end

end

app/models/charge_point.rb
class ChargePoint < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :vehicles
  has_many :trades
  has_many :connectors
  accepts_nested_attributes_for :users
end

app/models/connector.rb
class Connector < ActiveRecord::Base
  belongs_to :charge_point
  has_many :trades
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :author
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :trade
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  belongs_to :charge_point
  belongs_to :user
  belongs_to :vehicle
  belongs_to :connector
  has_many :records
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :charge_point
  belongs_to :user
  belongs_to :vehicle
end

app/models/user.rb
class User < ActiveRecord::Base
  #before_save { self.email = email.downcase }
  #validates :name, presence: true, length: { maximum: 50 }
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  #                  uniqueness: { case_sensitive: false }
  has_secure_password :validations => false
  #validates :password, length: { minimum: 6 }, :if => :password

  has_and_belongs_to_many :vehicles
  has_and_belongs_to_many :charge_points
  has_many :trades
  accepts_nested_attributes_for :charge_points
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  # has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  # validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_many :trades
  has_and_belongs_to_many :users
  has_and_belongs_to_many :charge_points
end

app/controllers/api/v1/trades_controller.rb
class Api::V1::TradesController < ApplicationController

  protect_from_forgery

  before_action :set_trade, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all
    respond_with @trades
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
    respond_with @trade
  end

  # GET /trades/new
  def new
    @trade = Trade.new
    respond_with @trade
  end

  # GET /trades/1/edit
  def edit
    respond_with @trade
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.json { render json: @trade, status: :created }
      else
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1
  # PATCH/PUT /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        #format.json { render :show, status: :ok, location: nil}
        format.json { render json: @trade, status: :ok }
      else
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.require(:trade).permit(:transaction_id, :status, :energy, :bill, :timestamp, :meter_start, :meter_stop)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	respond_to :json

	def index
		respond_with Post.all
	end

	def show
		respond_with Post.find(params[:id])
	end

	def create
		respond_with Post.create(post_params)
	end

	def update
		respond_with Post.update(params[:id], post_params)
	end

	def destroy
		respond_with Post.destroy(params[:id])
	end

	private
	def post_params
		params.require(:post).permit(:title, :intro, :extended, :published_at, :author)
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/task_controller.rb
class TaskController < WebsocketRails::BaseController
  def create
    # The `message` method contains the data received
    task = Task.new message
    if task.save
      send_message :create_success, task, :namespace => :tasks
    else
      send_message :create_fail, task, :namespace => :tasks
    end
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]

  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
  end

  # GET /trades/new
  def new
    @trade = Trade.new
  end

  # GET /trades/1/edit
  def edit
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'trade was successfully created.' }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1
  # PATCH/PUT /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to @trade, notice: 'trade was successfully updated.' }
        format.json { render :show, status: :ok, location: @trade }
      else
        format.html { render :edit }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url, notice: 'trade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.require(:trade).permit(:transaction_id, :status, :energy, :bill)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charge_points_helper.rb
module ChargePointsHelper
end

app/helpers/connectors_helper.rb
module ConnectorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/trades/_form.html.erb
<%= form_for(@trade) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_id %><br>
    <%= f.text_field :transaction_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :energy %><br>
    <%= f.text_field :energy %>
  </div>
  <div class="field">
    <%= f.label :bill %><br>
    <%= f.text_field :bill %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1>Listing trades</h1>

<table>
  <thead>
    <tr>
      <th>Transaction</th>
      <th>Status</th>
      <th>Energy</th>
      <th>Bill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td><%= trade.transaction_id %></td>
        <td><%= trade.status %></td>
        <td><%= trade.energy %></td>
        <td><%= trade.bill %></td>
        <td><%= link_to 'Show', trade %></td>
        <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
        <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction:</strong>
  <%= @trade.transaction_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @trade.status %>
</p>

<p>
  <strong>Energy:</strong>
  <%= @trade.energy %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @trade.bill %>
</p>

<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>